apiVersion: v1
kind: Namespace
metadata:
  name: saufautomat
---
apiVersion: v1
kind: Service
metadata:
  name: sauf-backend-service
  namespace: saufautomat
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: NodePort
  selector:
    app: saufautomat-backend
  ports:
    - name: http
      protocol: TCP
      port: 60001
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: saufautomat-backend-ingress
  namespace: saufautomat
spec:
  rules:
    - host: saufautom.at
      http:
        paths:
        - backend:
            serviceName: sauf-backend-service
            servicePort: 60001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saufautomat-backend
  namespace: saufautomat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saufautomat-backend
  template:
    metadata:
      labels:
        app: saufautomat-backend
    spec:
      containers:
      - name: saufautomat-backend
        image: openalcoholics/saufautomat{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
