name: Build/Publish docker image

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: "Build bundle.js"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.0.0"
      - run: npm install
      - run: npm run prod
      - uses: actions/upload-artifact@v1
        with:
          name: bundlejs
          path: public/bundle.js
  build_push_docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Login to dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u torbencarstens --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})
      - uses: actions/download-artifact@v1
        with:
          name: bundlejs
      - name: Build the tagged Docker image
        run: docker build -t openalcoholics/saufautomat:${{steps.vars.outputs.tag}} .
      - name: Push the tagged Docker image
        run: docker push openalcoholics/saufautomat:${{steps.vars.outputs.tag}}
  deploy:
    name: "Build dockerfile and deploy"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})
      - name: get kube config
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show torbencarstens > $GITHUB_WORKSPACE/.kubeconfig
      - name: update tag in manifest.yml
        run: sed -i -e "s#{{TAG}}#:$(echo ${{steps.vars.outputs.tag}})#g" .kubernetes/manifest.yaml
      - name: apply config
        run: kubectl -n drinkdome --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f .kubernetes/manifest.yaml
